import type { FunnelQuestion } from '../../types/funnel';

export const funnelQuestions: FunnelQuestion[] = [
  {
    id: 'q_first_name',
    key: 'firstName',
    step: 1,
    type: 'text',
    required: true,
    label: { fr: 'Votre prénom', de: 'Ihr Vorname' },
    placeholder: { fr: 'Jean', de: 'Mehdi' },
  },
  {
    id: 'q_whatsapp_phone',
    key: 'whatsappPhone',
    step: 1,
    type: 'phone',
    required: true,
    label: { fr: 'Téléphone', de: 'Telefon' },
    placeholder: { fr: '+33 6 12 34 56 78', de: '+49 170 1234567' },
  },
  {
    id: 'q_vehicle_type',
    key: 'vehicleType',
    step: 2,
    type: 'single_select',
    required: true,
    label: {
      fr: 'Quel type de véhicule recherchez-vous ?',
      de: 'Welche Fahrzeugart suchen Sie?',
    },
    options: [
      { value: 'suv', label: { fr: 'SUV', de: 'SUV' } },
      { value: 'sedan', label: { fr: 'Berline', de: 'Limousine' } },
      { value: 'wagon', label: { fr: 'Break', de: 'Kombi' } },
      { value: 'van', label: { fr: 'Monospace', de: 'Van' } },
      { value: 'other', label: { fr: 'Autre', de: 'Andere' } },
    ],
  },
  {
    id: 'q_brand',
    key: 'brand',
    step: 2,
    type: 'text',
    required: false,
    label: { fr: 'Marque souhaitée', de: 'Bevorzugte Marke' },
    placeholder: { fr: 'BMW, Mercedes, Audi...', de: 'BMW, Mercedes, Audi...' },
  },
  {
    id: 'q_budget_max',
    key: 'budgetMax',
    step: 3,
    type: 'number',
    required: true,
    label: { fr: 'Budget maximum', de: 'Budget bis' },
    placeholder: { fr: '25000', de: '25000' },
  },
  {
    id: 'q_destination_city',
    key: 'destinationCity',
    step: 3,
    type: 'city',
    required: true,
    label: { fr: 'Ville de livraison', de: 'Zielstadt' },
    placeholder: { fr: 'Lyon', de: 'Lyon' },
  },
  {
    id: 'q_notes',
    key: 'notes',
    step: 4,
    type: 'textarea',
    required: false,
    label: { fr: 'Autres souhaits', de: 'Weitere Wünsche' },
    placeholder: {
      fr: 'Couleur, options, delai...',
      de: 'Farbe, Ausstattung, Zeitraum...',
    },
  },
];
